#!/bin/sh

DIR=`pwd`

read -p "Install dotfiles? y/n: " yn
if [ $yn = "y" -o $yn = "Y" ]; then
  ln -vfs $DIR/nvim/init.lua $HOME/.config/nvim/init.lua

  ln -vfs $DIR/zsh/.zshrc $HOME/.zshrc
  ln -vfs $DIR/zsh/rc $HOME/

  ln -vfs $DIR/git/.gitconfig $HOME/.gitconfig

  ln -vfs $DIR/tmux/.tmux.conf $HOME/.tmux.conf
  echo "...done!"
fi

#echo ""
#read -p "Install some plugins from brew list? y/n: " yn
#if [ $yn = "y" -o $yn = "Y" ]; then
#  xargs brew install < $DIR/brew_list
#  echo "...done!"
#fi

echo ""
read -p "Never create .DS_Store? y/n: " yn
if [ $yn = "y" -o $yn = "Y" ]; then
  defaults write com.appli.desktopservices DSDontWriteNetworkStores true
  echo "...done!"
fi

echo ""
echo "Shell restarting ..."

exec $SHELL

